name: pygmt

channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.11  # <--- 主要修改點：將版本從 3.9 升級到 3.11
  - numpy
  - pandas
  - xarray
  - netcdf4
  - packaging
  - gmt
  - pygmt
  - obspy
  - jupyter
  - pip
  - git-lfs

  - pip:
    - streamlit
    - matplotlib
