name: Sync Fork

on:
  workflow_dispatch:   # 手動觸發
  schedule:            # 自動排程
    - cron: '0 2 * * *'  # 每天 UTC 02:00 執行 (台灣 10:00)

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false   # 使用 GITHUB_TOKEN push

      - name: Set up Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Add upstream
        run: git remote add upstream https://github.com/cwbdayi638/geophysics-class-2025.git

      - name: Fetch upstream
        run: git fetch upstream

      - name: Merge upstream
        run: |
          git checkout main
          git merge upstream/main || true

      - name: Push changes
        run: git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
